/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module cla(x1, x2, x3, x4, y1, y2, y3, y4, cin, z1, z2, z3, z4, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  input cin;
  wire cin;
  output cout;
  wire cout;
  wire g1;
  wire g2;
  wire g3;
  wire g4;
  wire k1;
  wire k2;
  wire k3;
  wire k4;
  wire l2;
  wire l3;
  wire l4;
  wire n2;
  wire n3;
  wire n4;
  wire p1;
  wire p2;
  wire p3;
  wire p4;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  input x4;
  wire x4;
  input y1;
  wire y1;
  input y2;
  wire y2;
  input y3;
  wire y3;
  input y4;
  wire y4;
  output z1;
  wire z1;
  output z2;
  wire z2;
  output z3;
  wire z3;
  output z4;
  wire z4;
  NOT _30_ (
    .A(cin),
    .Y(_00_)
  );
  NOT _31_ (
    .A(l3),
    .Y(_01_)
  );
  NOT _32_ (
    .A(n2),
    .Y(_02_)
  );
  NOT _33_ (
    .A(g1),
    .Y(_03_)
  );
  NOT _34_ (
    .A(n3),
    .Y(_04_)
  );
  NOT _35_ (
    .A(n4),
    .Y(_05_)
  );
  NOT _36_ (
    .A(p1),
    .Y(_06_)
  );
  NOT _37_ (
    .A(k1),
    .Y(_07_)
  );
  NOT _38_ (
    .A(k2),
    .Y(_08_)
  );
  NOT _39_ (
    .A(k4),
    .Y(_09_)
  );
  NAND _40_ (
    .A(cin),
    .B(l2),
    .Y(_10_)
  );
  NAND _41_ (
    .A(_02_),
    .B(_10_),
    .Y(_11_)
  );
  NAND _42_ (
    .A(l4),
    .B(_11_),
    .Y(_12_)
  );
  NAND _43_ (
    .A(_05_),
    .B(_12_),
    .Y(cout)
  );
  NAND _44_ (
    .A(cin),
    .B(_07_),
    .Y(_13_)
  );
  NAND _45_ (
    .A(_00_),
    .B(k1),
    .Y(_14_)
  );
  NAND _46_ (
    .A(_13_),
    .B(_14_),
    .Y(z1)
  );
  NOR _47_ (
    .A(_00_),
    .B(p1),
    .Y(_15_)
  );
  NAND _48_ (
    .A(cin),
    .B(_06_),
    .Y(_16_)
  );
  NOR _49_ (
    .A(_03_),
    .B(_15_),
    .Y(_17_)
  );
  NAND _50_ (
    .A(g1),
    .B(_16_),
    .Y(_18_)
  );
  NAND _51_ (
    .A(_08_),
    .B(_18_),
    .Y(_19_)
  );
  NAND _52_ (
    .A(k2),
    .B(_17_),
    .Y(_20_)
  );
  NAND _53_ (
    .A(_19_),
    .B(_20_),
    .Y(z2)
  );
  NAND _54_ (
    .A(k3),
    .B(_11_),
    .Y(_21_)
  );
  NOT _55_ (
    .A(_21_),
    .Y(_22_)
  );
  NOR _56_ (
    .A(k3),
    .B(_11_),
    .Y(_23_)
  );
  NOR _57_ (
    .A(_22_),
    .B(_23_),
    .Y(z3)
  );
  NOR _58_ (
    .A(_01_),
    .B(_17_),
    .Y(_24_)
  );
  NAND _59_ (
    .A(l3),
    .B(_18_),
    .Y(_25_)
  );
  NOR _60_ (
    .A(n3),
    .B(_24_),
    .Y(_26_)
  );
  NAND _61_ (
    .A(_04_),
    .B(_25_),
    .Y(_27_)
  );
  NAND _62_ (
    .A(k4),
    .B(_26_),
    .Y(_28_)
  );
  NAND _63_ (
    .A(_09_),
    .B(_27_),
    .Y(_29_)
  );
  NAND _64_ (
    .A(_28_),
    .B(_29_),
    .Y(z4)
  );
  clg clg2 (
    .g0(g1),
    .g1(g2),
    .l(l2),
    .n(n2),
    .p0(p1),
    .p1(p2)
  );
  clg clg3 (
    .g0(g2),
    .g1(g3),
    .l(l3),
    .n(n3),
    .p0(p2),
    .p1(p3)
  );
  clg clg4 (
    .g0(g3),
    .g1(g4),
    .l(l4),
    .n(n4),
    .p0(p3),
    .p1(p4)
  );
  pg pg1 (
    .g(g1),
    .k(k1),
    .p(p1),
    .x(x1),
    .y(y1)
  );
  pg pg2 (
    .g(g2),
    .k(k2),
    .p(p2),
    .x(x2),
    .y(y2)
  );
  pg pg3 (
    .g(g3),
    .k(k3),
    .p(p3),
    .x(x3),
    .y(y3)
  );
  pg pg4 (
    .g(g4),
    .k(k4),
    .p(p4),
    .x(x4),
    .y(y4)
  );
endmodule

module clg(p1, g1, p0, g0, l, n);
  wire _0_;
  wire _1_;
  input g0;
  wire g0;
  input g1;
  wire g1;
  output l;
  wire l;
  output n;
  wire n;
  input p0;
  wire p0;
  input p1;
  wire p1;
  NOR _2_ (
    .A(p1),
    .B(g0),
    .Y(_0_)
  );
  NOT _3_ (
    .A(_0_),
    .Y(_1_)
  );
  NAND _4_ (
    .A(g1),
    .B(_1_),
    .Y(n)
  );
  NOR _5_ (
    .A(p1),
    .B(p0),
    .Y(l)
  );
endmodule

module pg(x, y, p, g, k);
  wire _0_;
  output g;
  wire g;
  output k;
  wire k;
  output p;
  wire p;
  input x;
  wire x;
  input y;
  wire y;
  NOR _1_ (
    .A(x),
    .B(y),
    .Y(p)
  );
  NAND _2_ (
    .A(x),
    .B(y),
    .Y(g)
  );
  NOT _3_ (
    .A(g),
    .Y(_0_)
  );
  NOR _4_ (
    .A(p),
    .B(_0_),
    .Y(k)
  );
endmodule
