/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module four_bit_carry_increment_adder(A, Cin, Sum, Cout);
  input [3:0] A;
  wire [3:0] A;
  wire C2;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output [3:0] Sum;
  wire [3:0] Sum;
  two_bit_carry_lookahead_adder CLA0 (
    .A(A[1:0]),
    .B(2'b00),
    .Cin(Cin),
    .Cout(C2),
    .Sum(Sum[1:0])
  );
  two_bit_carry_lookahead_adder CLA1 (
    .A(A[3:2]),
    .B(2'b00),
    .Cin(C2),
    .Cout(Cout),
    .Sum(Sum[3:2])
  );
endmodule

module two_bit_carry_lookahead_adder(A, B, Cin, Sum, Cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output [1:0] Sum;
  wire [1:0] Sum;
  NOT _22_ (
    .A(A[0]),
    .Y(_21_)
  );
  NOT _23_ (
    .A(B[0]),
    .Y(_00_)
  );
  NOT _24_ (
    .A(Cin),
    .Y(_01_)
  );
  NAND _25_ (
    .A(A[1]),
    .B(B[1]),
    .Y(_02_)
  );
  NOT _26_ (
    .A(_02_),
    .Y(_03_)
  );
  NOR _27_ (
    .A(_21_),
    .B(_00_),
    .Y(_04_)
  );
  NAND _28_ (
    .A(A[0]),
    .B(B[0]),
    .Y(_05_)
  );
  NOR _29_ (
    .A(A[0]),
    .B(B[0]),
    .Y(_06_)
  );
  NOT _30_ (
    .A(_06_),
    .Y(_07_)
  );
  NOR _31_ (
    .A(_04_),
    .B(_06_),
    .Y(_08_)
  );
  NAND _32_ (
    .A(_05_),
    .B(_07_),
    .Y(_09_)
  );
  NOR _33_ (
    .A(_01_),
    .B(_09_),
    .Y(_10_)
  );
  NAND _34_ (
    .A(Cin),
    .B(_08_),
    .Y(_11_)
  );
  NOR _35_ (
    .A(_04_),
    .B(_10_),
    .Y(_12_)
  );
  NAND _36_ (
    .A(_05_),
    .B(_11_),
    .Y(_13_)
  );
  NOR _37_ (
    .A(A[1]),
    .B(B[1]),
    .Y(_14_)
  );
  NOR _38_ (
    .A(_03_),
    .B(_14_),
    .Y(_15_)
  );
  NOT _39_ (
    .A(_15_),
    .Y(_16_)
  );
  NOR _40_ (
    .A(_12_),
    .B(_16_),
    .Y(_17_)
  );
  NAND _41_ (
    .A(_13_),
    .B(_15_),
    .Y(_18_)
  );
  NAND _42_ (
    .A(_02_),
    .B(_18_),
    .Y(Cout)
  );
  NOR _43_ (
    .A(Cin),
    .B(_08_),
    .Y(_19_)
  );
  NOR _44_ (
    .A(_10_),
    .B(_19_),
    .Y(Sum[0])
  );
  NOR _45_ (
    .A(_13_),
    .B(_15_),
    .Y(_20_)
  );
  NOR _46_ (
    .A(_17_),
    .B(_20_),
    .Y(Sum[1])
  );
endmodule
